// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in user's id and email as seen by the MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var app_info_default = defineTool2({
  name: "app_info",
  title: "App info",
  description: "Describes the ServiceCRM app and the modules available: CRM (contacts, jobs & pipeline, quotes & invoices, forms), Marketing (Google Business, social organic/paid, email, Google Ads), Automations (workflows, sequences), and Analytics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "ServiceCRM",
      modules: {
        crm: ["contacts", "jobs & pipeline", "quotes & invoices", "forms"],
        marketing: [
          "google business profile",
          "social organic",
          "social paid",
          "email",
          "google ads"
        ],
        automations: ["workflows", "sequences"],
        analytics: ["reporting", "tracking"]
      },
      note: "Data is currently held in the browser; wire tools to Cloud tables to expose real records over MCP."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zxpiwazbclhkxvtuqwde";
var mcp_default = defineMcp({
  name: "servicecrm-mcp",
  title: "ServiceCRM",
  version: "0.1.0",
  instructions: "Tools for the ServiceCRM app. Use `whoami` to confirm the signed-in user and `app_info` to discover the app's modules.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
